### ISSUE TITLE
question(Solid_State_Telescope_(SST)_data.ipynb)

### ISSUE THREAD

**Issue by ZhengZhao123** [spedas/themis-examples#1]
use your code ,I have not run .
first ,I use spider editor to run ,and the result is none.
also ,I use jupyter notebook ,but it exists error in 'import pyspedas  from pytplot import tplot, options'

I want to plot a spectrum, but I have not related document about this. can you help me ?

**Comment by ericthewizard** [comment]
Sorry for the delay - just now seeing this! 

I ran the SST notebook, and it seems to run. If you're seeing an error importing pyspedas, it's probably due to an installation issue. Can you share the error you're seeing?
